// <auto-generated />
using System;
using Filminurk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Filminurk.Data.Migrations
{
    [DbContext(typeof(FilminurkTarpe24Context))]
    [Migration("20251204085243_nice")]
    partial class nice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Filminurk.Core.Domain.Actor", b =>
                {
                    b.Property<Guid>("ActorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("CareerStartYear")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoviesActedFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PortraitID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PrimarySpecialization")
                        .HasColumnType("int");

                    b.HasKey("ActorID");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.FileToApi", b =>
                {
                    b.Property<Guid>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExistingFilepath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsPoster")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MovieID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImageID");

                    b.ToTable("FilesToApi");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Actors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CurrentRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EntryCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EntryModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FirstPublished")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastWatched")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PeopleWatched")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.UserComment", b =>
                {
                    b.Property<Guid>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommentCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CommentDeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CommentModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CommentedScore")
                        .HasColumnType("int");

                    b.Property<string>("CommenterUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsHarmful")
                        .HasColumnType("int");

                    b.Property<int>("IsHelpful")
                        .HasColumnType("int");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommentID");

                    b.HasIndex("MovieId");

                    b.ToTable("UserComments");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.UserComment", b =>
                {
                    b.HasOne("Filminurk.Core.Domain.Movie", null)
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.Movie", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
