// <auto-generated />
using System;
using Filminurk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Filminurk.Data.Migrations
{
    [DbContext(typeof(FilminurkTARpe24Context))]
    [Migration("20260115122739_potat")]
    partial class potat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Filminurk.Core.Domain.Actor", b =>
                {
                    b.Property<Guid>("ActorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("CareerStartYear")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<Guid?>("FavouriteListID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoviesActedFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PortraitID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PrimarySpecialization")
                        .HasColumnType("int");

                    b.HasKey("ActorID");

                    b.HasIndex("FavouriteListID");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarImageID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentIDs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FavouriteListIDs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("ProfileType")
                        .HasColumnType("bit");

                    b.Property<int>("Reputation")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.FavouriteList", b =>
                {
                    b.Property<Guid>("FavouriteListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsMovieOrActor")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReported")
                        .HasColumnType("bit");

                    b.Property<string>("ListBelongsToUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ListCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ListDeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ListDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ListModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ListName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FavouriteListID");

                    b.ToTable("FavouriteLists");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.FileToApi", b =>
                {
                    b.Property<Guid>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExistingFilepath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsPoster")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MovieID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImageID");

                    b.ToTable("FilesToApi");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.FileToDatabase", b =>
                {
                    b.Property<Guid>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ListID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImageID");

                    b.ToTable("FilesToDatabase");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Actors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CurrentRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EntryCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EntryModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FavouriteListID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("FirstPublished")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastWatched")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PeopleWatched")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FavouriteListID");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.UserComment", b =>
                {
                    b.Property<Guid>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommentCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CommentDeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CommentModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CommentedScore")
                        .HasColumnType("int");

                    b.Property<string>("CommenterUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsHarmful")
                        .HasColumnType("int");

                    b.Property<int>("IsHelpful")
                        .HasColumnType("int");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommentID");

                    b.HasIndex("MovieId");

                    b.ToTable("UserComments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("identityRoles");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.Actor", b =>
                {
                    b.HasOne("Filminurk.Core.Domain.FavouriteList", null)
                        .WithMany("ListOfActors")
                        .HasForeignKey("FavouriteListID");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.Movie", b =>
                {
                    b.HasOne("Filminurk.Core.Domain.FavouriteList", null)
                        .WithMany("ListOfMovies")
                        .HasForeignKey("FavouriteListID");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.UserComment", b =>
                {
                    b.HasOne("Filminurk.Core.Domain.Movie", null)
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.FavouriteList", b =>
                {
                    b.Navigation("ListOfActors");

                    b.Navigation("ListOfMovies");
                });

            modelBuilder.Entity("Filminurk.Core.Domain.Movie", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
